language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
addons:
  apt:
    packages: libgsl-dev
  homebrew:
    packages: gsl
    update: true
script:
  - make
  - make lib
  - make examples/mat
  - make install
