language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
addons:
  apt:
    packages: libgsl-dev
  homebrew:
    packages: gsl
    update: true
jobs:
  include:
    - os: osx
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
        before_cache:
          - brew cleanup
script:
  - make
  - make lib
  - make examples/mat
  - DESTDIR="$PWD/pkg" make install
  - ls -R "$PWD/pkg"
