language: cpp

jobs:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - os: osx
      compiler: clang
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
        before_cache:
          - brew cleanup

addons:
  apt:
    packages: libgsl-dev
  homebrew:
    packages: gsl
    update: true

script:
  - make
  - make lib
  - make examples/mat
  - DESTDIR="$PWD/pkg" make install
  - ls -R "$PWD/pkg"
